-- drop FUNCTION RTSNG_PRD.RTSNG_F_GETSTAMFORMPERCLASS
CREATE FUNCTION RTSNG_PRD.RTSNG_F_GETSTAMFORMPERCLASS (
    @NOKA VARCHAR(50),
    @TRIPDATE DATE,
    @WAGONCLASSID INT
)
RETURNS TABLE
AS
RETURN (
    SELECT COUNT(S.C_STAMFORMDET_ID) AS COUNTSTAMFORM
    FROM RTSNG_PRD.RTSNG_T_STAMFORMDET S
    WHERE S.C_SCHEDULE_NOKA = @NOKA
      AND S.C_TRIP_DATE = @TRIPDATE
      AND S.C_STAMFORMDET_STATUS IN ('1','2')
      AND S.C_WAGONCLASS_ID = @WAGONCLASSID
);