-- drop FUNCTION RTSNG_PRD.RTSNG_F_GETFIRSTDEPARTURE

CREATE FUNCTION RTSNG_PRD.RTSNG_F_GETFIRSTDEPARTURE (
    @TRIPID INT,
    @STORDERORG INT,
    @STORDERORGDES INT
)
RETURNS TABLE
AS
RETURN (
    SELECT TOP 1
--  C_TRIP_DATE ||' ' ||C_STOP_DEPARTURE
  CONCAT(
    CAST(C_TRIP_DATE AS DATE), ' ',
    STUFF(RIGHT('0000' + C_STOP_DEPARTURE, 4), 3, 0, ':')
  ) AS DEPARTURE
  FROM RTSNG_PRD.RTSNG_T_ALLOCATION
  WHERE C_TRIP_ID = @TRIPID
    AND C_STOP_ORDERORG = @STORDERORG
    AND C_STOP_ORDERDES = @STORDERORGDES
    AND C_ALLOCATION_STATUS IN ('1','2','0')
);