CREATE FUNCTION RTSNG_PRD.RTSNG_F_GETFIRSTDEPARTUREs (
    @TRIPID INT,
    @ORDERORG INT,
    @ORDERDES INT
)
RETURNS DATETIME
AS
BEGIN
    DECLARE @DEPARTURE DATETIME;

    SELECT TOP 1 
        @DEPARTURE = TRY_CONVERT(DATETIME, FORMAT(C_TRIP_DATE, 'yyyy-MM-dd') + ' ' + 
                      STUFF(C_STOP_DEPARTURE, 3, 0, ':'), 120)
    FROM RTSNG_PRD.RTSNG_T_ALLOCATION
    WHERE C_TRIP_ID = @TRIPID
      AND C_STOP_ORDERORG = @ORDERORG
      AND C_STOP_ORDERDES = @ORDERDES
      AND C_ALLOCATION_STATUS IN ('1','2','0');

    RETURN @DEPARTURE;
END;