CREATE PROCEDURE RTSNG_PRD.USP_GETTRIPSUMMARY
    @TRIPDATE DATE
AS
BEGIN
    SET NOCOUNT ON;

    WITH MAINDATA AS (
        SELECT
            AR.C_AREA_NAME         AS AREAORG,
            TD.C_SCHEDULE_NOKA     AS TRAINNUMBER,
            S.C_TRAIN_NAME         AS TRAINNAME,
            RTSNG_PRD.RTSNG_F_GETFIRSTDEPARTURE(TD.C_TRIP_ID, 1, 2) AS DEPARTURE,
            TD.C_TRIP_DATE         AS TRIPDATE,
            TD.C_WAGONCLASS_CODE   AS WAGONCLASS,
            TD.C_STASIUN_CODEORG   AS ORG,
            TD.C_STASIUN_CODEDES   AS DES,
            RTSNG_PRD.RTSNG_F_GETMAXCAPCLSNOSEAT(
                TD.C_TRIP_ID,
                TD.C_SCHEDULE_NOKA,
                TD.C_TRIP_DATE,
                TD.C_WAGONCLASS_ID
            ) AS MAXCAPACITY,
            COUNT(TD.C_TRANSACTIONDET_ID) AS SUMPSG,
            RTSNG_PRD.RTSNG_F_GETSTAMFORMPERCLASS(
                TD.C_SCHEDULE_NOKA,
                TD.C_TRIP_DATE,
                TD.C_WAGONCLASS_ID
            ) AS COUNTSTAMFORM,
            SUM(TD.C_TRANSACTIONDET_AMOUNT) AS TOTFARE,
            SUM(DIS.C_TRANSDISTANCE_VALUE) AS DISTANCE,
            C_SCHEDULE_STAMFORM AS STAMFORM
        FROM
            RTSNG_PRD.RTSNG_T_TRANSACTIONDET AS TD
            INNER JOIN RTSNG_PRD.RTSNG_T_STASIUN        AS ST  ON ST.C_STASIUN_ID      = TD.C_STASIUN_IDORG
            INNER JOIN RTSNG_PRD.RTSNG_T_AREA           AS AR  ON AR.C_AREA_ID         = ST.C_AREA_ID
            INNER JOIN RTSNG_PRD.RTSNG_T_SCHEDULE       AS S   ON S.C_SCHEDULE_ID      = TD.C_SCHEDULE_ID
            LEFT  JOIN RTSNG_PRD.RTSNG_T_TRANSDISTANCE  AS DIS ON DIS.C_TRANSACTIONDET_TICKETNUM = TD.C_TRANSACTIONDET_TICKETNUM
        WHERE
            TD.C_TRANSACTIONDET_STATUS IN ('2', '5')
            AND TD.C_TRIP_DATE = @TRIPDATE
        GROUP BY
            AR.C_AREA_NAME,
            TD.C_SCHEDULE_NOKA,
            S.C_TRAIN_NAME,
            TD.C_TRIP_DATE,
            TD.C_TRIP_ID,
            TD.C_WAGONCLASS_CODE,
            TD.C_WAGONCLASS_ID,
            TD.C_STASIUN_CODEORG,
            TD.C_STASIUN_CODEDES,
            C_SCHEDULE_STAMFORM
    ),
    ZERODATA AS (
        SELECT
            AR.C_AREA_NAME         AS AREAORG,
            TP.C_SCHEDULE_NOKA     AS TRAINNUMBER,
            S.C_TRAIN_NAME         AS TRAINNAME,
            RTSNG_PRD.RTSNG_F_GETFIRSTDEPARTURE(TP.C_TRIP_ID, 1, 2) AS DEPARTURE,
            TP.C_TRIP_DATE         AS TRIPDATE,
            SD.C_WAGONCLASS_CODE   AS WAGONCLASS,
            DH.STASIUNCODEORG      AS ORG,
            DH.STASIUNCODEDES      AS DES,
            RTSNG_PRD.RTSNG_F_GETMAXCAPCLSNOSEAT(
                TP.C_TRIP_ID,
                TP.C_SCHEDULE_NOKA,
                TP.C_TRIP_DATE,
                SD.C_WAGONCLASS_ID
            ) AS MAXCAPACITY,
            0                      AS SUMPSG,
            RTSNG_PRD.RTSNG_F_GETSTAMFORMPERCLASS(
                TP.C_SCHEDULE_NOKA,
                TP.C_TRIP_DATE,
                SD.C_WAGONCLASS_ID
            ) AS COUNTSTAMFORM,
            0                      AS TOTFARE,
            0                      AS DISTANCE,
            C_SCHEDULE_STAMFORM AS STAMFORM
        FROM
            RTSNG_PRD.RTSNG_T_TRIP           AS TP
            INNER JOIN RTSNG_PRD.RTSNG_T_STAMFORMDET AS SD ON SD.C_TRIP_ID = TP.C_TRIP_ID
            LEFT  JOIN RTSNG_PRD.RTSNG_T_SCHEDULE     AS S  ON S.C_SCHEDULE_ID = TP.C_SCHEDULE_ID
            LEFT  JOIN RTSNG_PRD.RTSNG_T_DASHBOARDKA  AS DH ON DH.NO_KA = TP.C_SCHEDULE_NOKA
                AND TP.C_TRIP_DATE BETWEEN DH.STARTDATE AND DH.ENDDATE
            LEFT  JOIN RTSNG_PRD.RTSNG_T_STASIUN      AS ST ON ST.C_STASIUN_ID = DH.STASIUNCODEORG
            LEFT  JOIN RTSNG_PRD.RTSNG_T_AREA         AS AR ON AR.C_AREA_ID    = ST.C_AREA_ID
        WHERE
            TP.C_TRIP_STATUS = '1'
    )
    SELECT * FROM MAINDATA
    UNION ALL
    SELECT * FROM ZERODATA
    ORDER BY
        TRIPDATE DESC,
        WAGONCLASS DESC,
        TRAINNUMBER ASC;
END