-- Auto Generated (Do not modify) 5EB54676F0BA5D234BDF5A900E0FC234AE11BA9AE53B2DADE5A157345A8B4394
CREATE   VIEW RTSNG_PRD.V_TRIPDATA_MAXCAPACITY AS
SELECT
  DU.C_TRIP_ID,
  DU.C_SCHEDULE_NOKA,
  DU.C_TRIP_DATE,
  DU.C_WAGONCLASS_ID,
  RTSNG_PRD.RTSNG_F_GETMAXCAPCLSNOSEAT(
    DU.C_TRIP_ID,
    DU.C_SCHEDULE_NOKA,
    DU.C_TRIP_DATE,
    DU.C_WAGONCLASS_ID
  ) AS MAXCAPACITY
FROM RTSNG_PRD.V_TRIPDATA_UTAMA DU;