-- Auto Generated (Do not modify) 43712F9891531EE0AEB39B5B69B182B566309FDC8CDB0D9B909EABCCDEB87FF6
CREATE   VIEW RTSNG_PRD.V_TRIPDATA_UTAMA AS
SELECT
  TD.C_TRIP_ID,
  TD.C_SCHEDULE_NOKA,
  TD.C_TRIP_DATE,
  TD.C_WAGONCLASS_ID,
  TD.C_WAGONCLASS_CODE,
  COUNT(*) AS SUM_PSG,
  SUM(TD.C_TRANSACTIONDET_AMOUNT) AS TOTFARE
FROM RTSNG_PRD.RTSNG_T_TRANSACTIONDET TD
WHERE TD.C_TRANSACTIONDET_STATUS IN ('2', '5')
GROUP BY
  TD.C_TRIP_ID,
  TD.C_SCHEDULE_NOKA,
  TD.C_TRIP_DATE,
  TD.C_WAGONCLASS_ID,
  TD.C_WAGONCLASS_CODE;