-- Auto Generated (Do not modify) 10A89D49F117F70886BB4C59A6B8554252AEAD7BCDAD74C041EBDAB240F9213C
CREATE   VIEW RTSNG_PRD.V_TRIPDATA_FINAL AS
SELECT
  DU.C_TRIP_ID,
  DU.C_SCHEDULE_NOKA,
  DU.C_TRIP_DATE,
  DU.C_WAGONCLASS_ID,
  DU.C_WAGONCLASS_CODE,
  DU.SUM_PSG,
  DU.TOTFARE,
  FC.MAXCAPACITY,
  FS.COUNTSTAMFORM
FROM RTSNG_PRD.V_TRIPDATA_UTAMA DU
LEFT JOIN RTSNG_PRD.V_TRIPDATA_MAXCAPACITY FC
  ON DU.C_TRIP_ID = FC.C_TRIP_ID
  AND DU.C_SCHEDULE_NOKA = FC.C_SCHEDULE_NOKA
  AND DU.C_TRIP_DATE = FC.C_TRIP_DATE
  AND DU.C_WAGONCLASS_ID = FC.C_WAGONCLASS_ID
LEFT JOIN RTSNG_PRD.V_TRIPDATA_STAMFORM FS
  ON DU.C_SCHEDULE_NOKA = FS.C_SCHEDULE_NOKA
  AND DU.C_TRIP_DATE = FS.C_TRIP_DATE
  AND DU.C_WAGONCLASS_ID = FS.C_WAGONCLASS_ID;