CREATE TABLE [RTSNG_PRD].[RTSNG_T_CANCELLATIONTYPE] (

	[C_CANCELLATIONTYPE_ID] bigint NULL, 
	[C_CANCELLATIONTYPE_NAME] varchar(100) NULL, 
	[C_CANCELLATIONTYPE_STATUS] varchar(1) NULL, 
	[C_CANCELLATIONTYPE_DOMAIN] bigint NULL, 
	[C_CANCELLATIONTYPE_MODIFIEDBY] bigint NULL, 
	[C_CANCELLATIONTYPE_MODIFIEDON] datetime2(6) NULL, 
	[C_CANCELLATIONTYPE_CODE] varchar(50) NULL, 
	[C_CANCELLATIONTYPE_CREATEDBY] bigint NULL, 
	[C_CANCELLATIONTYPE_CREATEDON] datetime2(6) NULL
);