CREATE TABLE [RTSNG_PRD].[RTSNG_T_DASHBOARDKA] (

	[ID] bigint NULL, 
	[NO_KA] varchar(10) NULL, 
	[NAMA_KA] varchar(50) NULL, 
	[LOKAL_STAT] bigint NULL, 
	[PRIORITY] bigint NULL, 
	[ORDERORG] bigint NULL, 
	[ORDERDES] bigint NULL, 
	[STASIUNCODEORG] varchar(50) NULL, 
	[STASIUNCODEDES] varchar(50) NULL, 
	[PSO] bigint NULL, 
	[JARAK_PARSIAL] decimal(18,5) NULL, 
	[JARAK_OD] decimal(18,5) NULL, 
	[JARAK_KHUSUS] decimal(18,5) NULL, 
	[PSO2017] bigint NULL, 
	[NAMA_KA_2017] varchar(50) NULL, 
	[STATUS] varchar(1) NULL, 
	[LOKAL_STAT2017] bigint NULL, 
	[LUXURY] bigint NULL, 
	[KCI] bigint NULL, 
	[PERINTIS] bigint NULL, 
	[STARTDATE] datetime2(6) NULL, 
	[ENDDATE] datetime2(6) NULL, 
	[WILAYAH] bigint NULL, 
	[CREATEDON] datetime2(6) NULL, 
	[CREATEDBY] varchar(50) NULL, 
	[MODIFIEDON] datetime2(6) NULL, 
	[MODIFIEDBY] varchar(50) NULL, 
	[EMISI_EKO] decimal(18,10) NULL, 
	[EMISI_BIS] decimal(18,10) NULL, 
	[EMISI_EKS] decimal(18,10) NULL, 
	[EMISI_PANO] decimal(18,10) NULL, 
	[EMISI_LUX] decimal(18,10) NULL, 
	[EMISI_LUXS] decimal(18,10) NULL, 
	[EMISI_COMP] decimal(18,10) NULL, 
	[EMISI_PRIO] decimal(18,10) NULL
);