CREATE TABLE [RTSNG_PRD].[RTSNG_T_CANCELTRAIN] (

	[C_CANCELTRAIN_ID] bigint NULL, 
	[C_CANCELTRAIN_NOKA] varchar(50) NULL, 
	[C_CANCELTRAIN_STARTDATE] datetime2(6) NULL, 
	[C_CANCELTRAIN_ENDDATE] datetime2(6) NULL, 
	[C_CANCELTRAIN_STATUS] varchar(1) NULL, 
	[C_STASIUN_ORDERORG] bigint NULL, 
	[C_STASIUN_ORDERDES] bigint NULL, 
	[C_STASIUN_CODEORG] varchar(5) NULL, 
	[C_STASIUN_CODEDES] varchar(5) NULL, 
	[C_CANCELTRAIN_CREATEDBY] bigint NULL, 
	[C_CANCELTRAIN_CREATEDON] datetime2(6) NULL, 
	[C_CANCELTRAIN_MODIFIEDBY] bigint NULL, 
	[C_CANCELTRAIN_MODIFIEDON] datetime2(6) NULL, 
	[C_STASIUN_ORGSTOP] varchar(1) NULL, 
	[C_STASIUN_DESSTART] varchar(1) NULL
);