CREATE TABLE [RTSNG_PRD].[RTSNG_T_CANCELREASON] (

	[C_CANCELREASON_ID] bigint NULL, 
	[C_CANCELREASON_DESC] varchar(100) NULL, 
	[C_CANCELREASON_STATUS] varchar(1) NULL, 
	[C_CANCELREASON_PERCENT] bigint NULL, 
	[C_CANCELREASON_ROLE] varchar(1) NULL, 
	[C_CANCELREASON_CREATEDBY] bigint NULL, 
	[C_CANCELREASON_CREATEDON] datetime2(6) NULL, 
	[C_CANCELREASON_MODIFIEDBY] bigint NULL, 
	[C_CANCELREASON_MODIFIEDON] datetime2(6) NULL
);