CREATE TABLE [RTSNG_PRD].[RTSNG_T_STAMFORMDET] (

	[C_STAMFORMDET_ID] bigint NULL, 
	[C_STAMFORMDET_ORDER] bigint NULL, 
	[C_STAMFORMDET_STATUS] varchar(1) NULL, 
	[C_STAMFORMDET_DOMAIN] bigint NULL, 
	[C_STAMFORMDET_MODIFIEDBY] bigint NULL, 
	[C_STAMFORMDET_MODIFIEDON] datetime2(6) NULL, 
	[C_WAGON_ID] bigint NULL, 
	[C_TRIP_ID] varchar(36) NULL, 
	[C_STAMFORMDET_CREATEDBY] bigint NULL, 
	[C_STAMFORMDET_CREATEDON] datetime2(6) NULL, 
	[C_SCHEDULE_NOKA] varchar(10) NULL, 
	[C_TRIP_DATE] datetime2(6) NULL, 
	[C_WAGONCLASS_ID] bigint NULL, 
	[C_WAGONCLASS_CODE] varchar(10) NULL, 
	[C_WAGON_NAME] varchar(100) NULL, 
	[C_WAGON_FACILITYCODE] varchar(20) NULL
);