CREATE TABLE [RTSNG_PRD].[RTSNG_T_TRAINMILES] (

	[C_TRAINMILES_ID] bigint NULL, 
	[C_TRAINMILES_NAME] varchar(100) NULL, 
	[C_TRAINMILES_STATUS] varchar(1) NULL, 
	[C_TRAINMILES_DOMAIN] bigint NULL, 
	[C_TRAINMILES_MODIFIEDBY] bigint NULL, 
	[C_TRAINMILES_MODIFIEDON] datetime2(6) NULL, 
	[C_TRAINMILES_CREATEDBY] bigint NULL, 
	[C_TRAINMILES_CREATEDON] datetime2(6) NULL, 
	[C_TRAINMILES_CODE] varchar(10) NULL, 
	[C_TRAINMILES_NOTE] varchar(200) NULL, 
	[C_TRAINMILES_SORT] varchar(1) NULL
);