CREATE TABLE [RTSNG_PRD].[RTSNG_T_TRAINTYPE] (

	[C_TRAINTYPE_ID] bigint NULL, 
	[C_TRAINTYPE_NAME] varchar(100) NULL, 
	[C_TRAINTYPE_STATUS] varchar(1) NULL, 
	[C_TRAINTYPE_DOMAIN] bigint NULL, 
	[C_TRAINTYPE_MODIFIEDBY] bigint NULL, 
	[C_TRAINTYPE_MODIFIEDON] datetime2(6) NULL, 
	[C_TRAINTYPE_CODE] varchar(10) NULL, 
	[C_TRAINTYPE_CREATEDBY] bigint NULL, 
	[C_TRAINTYPE_CREATEDON] datetime2(6) NULL, 
	[C_TRAINTYPE_NOTE] varchar(100) NULL, 
	[C_TRAINTYPE_PAYPOIN] varchar(1) NULL, 
	[C_TRAINTYPE_GETPOIN] varchar(1) NULL, 
	[C_TRAINTYPE_SORT] varchar(1) NULL
);